Repository adobecom/bacom, pull requests merged in 2023-03, with the labels that each got.

#85 [MWPW-126441] Unblock style-linting by lowercasing all t-shirt sizes in classnames
  blocks/event-speakers/event-speakers.js
  blocks/stats/stats.js
  blocks/tree-view/tree-view.js
  test/blocks/stats/stats.test.js
Labels: enhancement, do not merge, trivial

#88 Add codeql
  .github/codeql/codeql-config.yml
  .github/workflows/codeql.yml
Labels: trivial

#90 Enable Locales tool in sidekick
  tools/sidekick/config.json
Labels: verified, trivial
