Repository adobecom/bacom, pull requests merged in 2023-04, with the labels that each got.

#94 MWPW-129144 Breadcrumb home report - de
  helix-query.yaml
Labels: trivial

#96 MWPW-129144 Index customer stories ROW
  helix-query.yaml
Labels: trivial

#93 MWPW-125597 - Enable cta config
  blocks/chat-cta/chat-cta.css
  blocks/chat-cta/chat-cta.js
  scripts/scripts.js
  test/blocks/chat-cta/chat-cta.test.js
Labels: verified

#99 MWPW-129025 Index intl customer story videos
  helix-query.yaml
Labels: trivial

#100 MWPW-129025 Fix video index
  helix-query.yaml
Labels: trivial

#101 Adding Nala workflow to Github actions
  .github/workflows/run-nala.yaml
Labels: trivial, run-nala, @failedblock
