Repository adobecom/bacom, pull requests merged in 2023-06, with the labels that each got.

#118 MWPW-125482 Add dir property to rtl locales
  scripts/scripts.js
Labels: verified

#121 MWPW-131894 fix checkbox height
  styles/faas.css
Labels: verified

#124 Update PR template
  .github/pull_request_template.md
Labels: trivial

#126 MWPW-133230 Add why-adobe and support to sitemap
  helix-query.yaml
Labels: do not merge, trivial

#127 MWPW-133230 why-adobe and support for US sitemap
  helix-query.yaml
Labels: trivial
