Repository adobecom/bacom, pull requests merged in 2023-05, with the labels that each got.

#105 Fix layout shift for FaaS
  scripts/scripts.js
Labels: feature branch

#104 MWPW-129397 Clearbit FaaS Enabled Styles
  styles/faas.css
Labels: feature branch

#107 MWPW-128620 FaaS Form 115 Styles
  styles/faas.css
Labels: feature branch

#109 MWPW-129587 FaaS Styles
  styles/faas.css
Labels: feature branch

#110 FaaS Styles feature branch to Main
  scripts/scripts.js
  styles/faas.css
Labels: verified

#111 MWPW-130076 US Resource Query Index
  helix-query.yaml
Labels: trivial

#112 MWPW-130076 Resource Index Text Selector
  helix-query.yaml
Labels: trivial

#113 MWPW-130076 FaaS Decode
  blocks/faas-decode/faas-decode.css
  blocks/faas-decode/faas-decode.js
  test/blocks/faas-decode/faas-decode.test.js
  test/blocks/faas-decode/mocks/query-index.json
  test/helpers/waitForElement.js
Labels: trivial

#114 MWPW-131411 Add internal campaign id to report
  blocks/faas-decode/faas-decode.css
  blocks/faas-decode/faas-decode.js
Labels: trivial

#116 Removing load delayed as per Narcis comment on Slack
  scripts/scripts.js
Labels: verified, trivial

#115 Eager load all marquee images
  scripts/scripts.js
Labels: verified
