Repository adobecom/bacom, pull requests merged in 2023-07, with the labels that each got.

#128 MWPW-133167 CaaS CLS Issue
  styles/styles.css
Labels: verified

#129 MWPW-132487 Fix noindex pages in sitemap
  helix-query.yaml
Labels: trivial

#132 MWPW-134103 Fix Blog Regex
  scripts/scripts.js
Labels: bug
