Repository adobecom/bacom, pull requests merged in 2024-03, with the labels that each got.

#179 MWPW-141660...64: Redirect Formatter Fixes
  blocks/redirects-formatter/redirects-formatter.css
  blocks/redirects-formatter/redirects-formatter.js
  test/blocks/redirects-formatter/mocks/textAreaValues.js
  test/blocks/redirects-formatter/redirects-formatter.test.js
Labels: verified

#181 MWPW-143973: CLS Issue with Grid Width
  styles/styles.css
Labels: verified

#182 MWPW-144537 Remove MT and CY_EN sitemaps
  helix-query.yaml
  helix-sitemap.yaml
Labels: trivial

#183 MWPW-143582 Remove copyright comments
  blocks/stats/stats.js
  scripts/scripts.js
  scripts/utils.js
  styles/styles.css
  tools/sidekick/config.js
Labels: trivial, run-bacom-live

#184 MWPW-143708: Create Kodiak config.yaml
  .kodiak/config.yaml
Labels: trivial, security

#185 Stage to Main
  .kodiak/config.yaml
  blocks/stats/stats.js
  helix-query.yaml
  helix-sitemap.yaml
  scripts/scripts.js
  scripts/utils.js
  styles/styles.css
  tools/sidekick/config.js
Labels: trivial
