Repository adobecom/bacom, pull requests merged in 2024-01, with the labels that each got.

#164 MWPW-138379 Add publish date to all query indexes
  helix-query.yaml
Labels: trivial

#165 MWPW-138379 Query index date format
  helix-query.yaml
Labels: trivial

#167 MWPW-141206 AA University in Marketo
  scripts/aa-university.js
  scripts/scripts.js
  test/helpers/generalHelpers.js
  test/scripts/aa-university.test.js
  test/scripts/mocks/body.html
  web-test-runner.config.mjs
Labels: verified

#166 MWPW-139819 Redirect Formatter PoC
  blocks/redirects-formatter/redirects-formatter.css
  blocks/redirects-formatter/redirects-formatter.js
  test/blocks/redirects-formatter/mocks/locale-config.json
  test/blocks/redirects-formatter/mocks/redirects-formatter.html
  test/blocks/redirects-formatter/mocks/textAreaValues.js
  test/blocks/redirects-formatter/redirects-formatter.test.js
Labels: enhancement
