Repository adobecom/bacom, pull requests merged in 2024-07, with the labels that each got.

#224 MWPW-154562 Fix resource form margins
  styles/styles.css
Labels: bug, verified, ready for stage

#223 MWPW-154250 Update India lang code
  scripts/scripts.js
Labels: verified, run-nala, ready for stage

#230 MWPW-145389 Push sync for floodgate and graybox
  .github/workflows/fg-sync-repos.yml
Labels: zero-impact

#229 [Release] Stage to Main
  .github/workflows/fg-sync-repos.yml
  .github/workflows/graybox-sync-repos.yml
Labels: zero-impact

#217 MWPW-143579 Log 404s to lana
  scripts/scripts.js
Labels: verified, ready for stage

#231 [Release] Stage to Main
  scripts/scripts.js
Labels: run-nala
